### ISSUE TITLE
RoR group project: set up your Kanban board

### ISSUE THREAD

**Issue by zuhebahmed88091** [zuhebahmed88091/Recipe_app#20]
We are 2 members in this capstone
---

@MesakDuduCoder  :  Mesak Lalrindika
@zuhebahmed88091  : Zuheb Ahmed

This is our project [link](https://github.com/zuhebahmed88091/Recipe_app/projects/1)

**Comment by uwadonat** [comment]
## Hi @Team,

Your Kanban board is well set up. There is nothing else to say other than... it's time to move on to the next milestone. :shipit: 
### Congratulations! 🎉 
![gooo](https://github.com/zuhebahmed88091/Recipe_app/assets/65860678/0ca6ae9e-a905-49ba-98d5-650b104dad3c)

# Status: Approved ✔️✔️✔️

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100%.
Please, remember to tag me @uwadonat in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```
